import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import  './globals.css'
import React from "react";
import {QueryProvider} from '@/components/providers/QueryProvider'
const poppins = Poppins({
	subsets: ["latin"],
	weight: ["100", "300", "400", "500", "600", "700", "800"], // all weights you need
	display: "swap", // ensures text remains visible during font load
	variable: "--font-poppins", // optional: if you want to use CSS variables
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
									   children,
								   }: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={poppins.variable}
		>
			<body>
				<QueryProvider>
					{children}
				</QueryProvider>
			</body>
		</html>
	);
}
